services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    # 로컬의 src 폴더를 컨테이너의 /app에 마운트합니다.
    volumes:
      - ./src:/app
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
